name = "jona"
description = "Static site generator"
version = "0.0.1"

authors = ["Jesper Quorning"]
maintainers = ["Jesper Quorning <jesper.quorning@gmail.com>"]
maintainers-logins = ["jquorning"]
licenses = "MIT OR Apache-2.0"
website = ""
tags = ["jona", "yass"]

executables = ["jona"]
